name = "keendreams"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[vars]
ALLOWED_ORIGINS = "*"

[[kv_namespaces]]
binding = "DREAMS"
id = "your_kv_namespace_id"
preview_id = "your_preview_kv_namespace_id"

[[kv_namespaces]]
binding = "PROJECTS"
id = "your_projects_kv_id"
preview_id = "your_projects_preview_id"

[env.production]
route = "keendreams.*.workers.dev/*"